version: "3.3"
services:
  database:
    image: postgres:16.1-alpine3.19
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: handball_analyzer
      POSTGRES_PASSWORD: handball_analyzer
      POSTGRES_DB: handball_analyzer
    volumes:
      - database_data:/var/lib/postgresql/data

volumes:
  database_data:
    driver: local
