// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: game-event-goals.queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listGameGoals = `-- name: ListGameGoals :many
SELECT id, uid, game_id, team_id, team_member_id, daytime, elapsed_seconds, score_home, score_away, created_at, updated_at, deleted_at FROM game_event_goals WHERE game_id = $1 ORDER BY elapsed_seconds
`

func (q *Queries) ListGameGoals(ctx context.Context, gameID int64) ([]GameEventGoal, error) {
	rows, err := q.db.Query(ctx, listGameGoals, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameEventGoal
	for rows.Next() {
		var i GameEventGoal
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.GameID,
			&i.TeamID,
			&i.TeamMemberID,
			&i.Daytime,
			&i.ElapsedSeconds,
			&i.ScoreHome,
			&i.ScoreAway,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGameEventGoal = `-- name: UpsertGameEventGoal :one
INSERT INTO
    game_event_goals (uid, game_id, team_id, team_member_id, daytime, elapsed_seconds, score_home, score_away)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) ON CONFLICT (uid)
DO
UPDATE
SET
    updated_at = NOW() RETURNING id, uid, game_id, team_id, team_member_id, daytime, elapsed_seconds, score_home, score_away, created_at, updated_at, deleted_at
`

type UpsertGameEventGoalParams struct {
	Uid            string
	GameID         int64
	TeamID         int64
	TeamMemberID   int64
	Daytime        pgtype.Timestamptz
	ElapsedSeconds int32
	ScoreHome      int32
	ScoreAway      int32
}

func (q *Queries) UpsertGameEventGoal(ctx context.Context, arg UpsertGameEventGoalParams) (GameEventGoal, error) {
	row := q.db.QueryRow(ctx, upsertGameEventGoal,
		arg.Uid,
		arg.GameID,
		arg.TeamID,
		arg.TeamMemberID,
		arg.Daytime,
		arg.ElapsedSeconds,
		arg.ScoreHome,
		arg.ScoreAway,
	)
	var i GameEventGoal
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.GameID,
		&i.TeamID,
		&i.TeamMemberID,
		&i.Daytime,
		&i.ElapsedSeconds,
		&i.ScoreHome,
		&i.ScoreAway,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
