// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: games-referees.queries.sql

package db

import (
	"context"
)

const upsertGameReferee = `-- name: UpsertGameReferee :exec
INSERT INTO
    games_referees (game_id, referee_id)
VALUES ($1, $2) ON CONFLICT (game_id, referee_id)
DO
NOTHING
`

type UpsertGameRefereeParams struct {
	GameID    int64
	RefereeID int64
}

func (q *Queries) UpsertGameReferee(ctx context.Context, arg UpsertGameRefereeParams) error {
	_, err := q.db.Exec(ctx, upsertGameReferee, arg.GameID, arg.RefereeID)
	return err
}
