// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: game-event-seven-meters.queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listGameSevenMeters = `-- name: ListGameSevenMeters :many
SELECT id, uid, game_id, team_id, team_member_id, daytime, elapsed_seconds, is_goal, score_home, score_away, created_at, updated_at, deleted_at FROM game_event_seven_meters WHERE game_id = $1 ORDER BY elapsed_seconds
`

func (q *Queries) ListGameSevenMeters(ctx context.Context, gameID int64) ([]GameEventSevenMeter, error) {
	rows, err := q.db.Query(ctx, listGameSevenMeters, gameID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GameEventSevenMeter
	for rows.Next() {
		var i GameEventSevenMeter
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.GameID,
			&i.TeamID,
			&i.TeamMemberID,
			&i.Daytime,
			&i.ElapsedSeconds,
			&i.IsGoal,
			&i.ScoreHome,
			&i.ScoreAway,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertGameEventSevenMeter = `-- name: UpsertGameEventSevenMeter :one
INSERT INTO
    game_event_seven_meters (uid, game_id, team_id, team_member_id, daytime, elapsed_seconds, is_goal, score_home, score_away)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9) ON CONFLICT (uid)
DO
UPDATE
SET
    updated_at = NOW() RETURNING id, uid, game_id, team_id, team_member_id, daytime, elapsed_seconds, is_goal, score_home, score_away, created_at, updated_at, deleted_at
`

type UpsertGameEventSevenMeterParams struct {
	Uid            string
	GameID         int64
	TeamID         int64
	TeamMemberID   int64
	Daytime        pgtype.Timestamptz
	ElapsedSeconds int32
	IsGoal         bool
	ScoreHome      int32
	ScoreAway      int32
}

func (q *Queries) UpsertGameEventSevenMeter(ctx context.Context, arg UpsertGameEventSevenMeterParams) (GameEventSevenMeter, error) {
	row := q.db.QueryRow(ctx, upsertGameEventSevenMeter,
		arg.Uid,
		arg.GameID,
		arg.TeamID,
		arg.TeamMemberID,
		arg.Daytime,
		arg.ElapsedSeconds,
		arg.IsGoal,
		arg.ScoreHome,
		arg.ScoreAway,
	)
	var i GameEventSevenMeter
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.GameID,
		&i.TeamID,
		&i.TeamMemberID,
		&i.Daytime,
		&i.ElapsedSeconds,
		&i.IsGoal,
		&i.ScoreHome,
		&i.ScoreAway,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
