// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Game struct {
	ID                int64
	Uid               string
	Date              pgtype.Timestamptz
	LeagueID          int64
	HomeTeamID        int64
	AwayTeamID        int64
	HalftimeHomeScore int32
	HalftimeAwayScore int32
	FulltimeHomeScore int32
	FulltimeAwayScore int32
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DeletedAt         pgtype.Timestamptz
}

type GameEventBlueCard struct {
	ID             int64
	Uid            string
	GameID         int64
	TeamID         int64
	TeamMemberID   int64
	Daytime        pgtype.Timestamptz
	ElapsedSeconds int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type GameEventGoal struct {
	ID             int64
	Uid            string
	GameID         int64
	TeamID         int64
	TeamMemberID   int64
	Daytime        pgtype.Timestamptz
	ElapsedSeconds int32
	ScoreHome      int32
	ScoreAway      int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type GameEventPenalty struct {
	ID             int64
	Uid            string
	GameID         int64
	TeamID         int64
	TeamMemberID   pgtype.Int8
	Daytime        pgtype.Timestamptz
	ElapsedSeconds int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type GameEventRedCard struct {
	ID             int64
	Uid            string
	GameID         int64
	TeamID         int64
	TeamMemberID   int64
	Daytime        pgtype.Timestamptz
	ElapsedSeconds int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type GameEventSevenMeter struct {
	ID             int64
	Uid            string
	GameID         int64
	TeamID         int64
	TeamMemberID   int64
	Daytime        pgtype.Timestamptz
	ElapsedSeconds int32
	IsGoal         bool
	ScoreHome      int32
	ScoreAway      int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type GameEventTimeout struct {
	ID             int64
	Uid            string
	GameID         int64
	TeamID         int64
	Daytime        pgtype.Timestamptz
	ElapsedSeconds int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type GameEventYellowCard struct {
	ID             int64
	Uid            string
	GameID         int64
	TeamID         int64
	TeamMemberID   pgtype.Int8
	Daytime        pgtype.Timestamptz
	ElapsedSeconds int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	DeletedAt      pgtype.Timestamptz
}

type GamesReferee struct {
	GameID    int64
	RefereeID int64
}

type League struct {
	ID        int64
	Uid       string
	SeasonID  int64
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Referee struct {
	ID        int64
	Uid       string
	Name      string
	Type      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Season struct {
	ID        int64
	Uid       string
	StartDate pgtype.Timestamptz
	EndDate   pgtype.Timestamptz
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type Team struct {
	ID        int64
	Uid       string
	LeagueID  int64
	Name      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}

type TeamMember struct {
	ID        int64
	Uid       string
	TeamID    int64
	Name      string
	Number    string
	Type      string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	DeletedAt pgtype.Timestamptz
}
